.TH "sawfish-config" "1"
.SH "NAME"
sawfish-config \(em The Sawfish Configurator.
.SH "SYNOPSIS"
.PP
\fBsawfish-config\fR [\fB \-\-group=\fIGROUP-NAME \fR\fP]  [\fB \-\-flatten \fP]
.SH "DESCRIPTION"
.PP
This program can be used to manually invoke the Sawfish configurator, but
usually it's called from the window manager itself.
.SH "OPTIONS"
.IP "\fB\-\-group=\fIGROUP-NAME\fP 	" 10
Display only \fIGROUP-NAME\fR.
.IP "" 10
\fIGROUP-NAME\fR should be one of these names: Sawfish, Appearance,
Bindings, Focus, Minimizing/Maximizing, Miscellaneous, Move/Resize,
Sounds, Window Rules, Workspaces
.IP "\fB\-\-flatten\fP" 10
display sub-groups inline instead of using a tree widget. In normal
`tree' item, don't put frame the widgets
.IP "\fB\-\-disable-nls\fP" 10
Disable internationalization of messages.
.IP "\fB\-\-help\fP" 10
Prints help.
.SH "AUTHOR"
.PP
This manual page was written by Christian Marillat marillat@debian.org for
the \fBDebian GNU/Linux\fP system (but may be used by others).
.\" created by instant / docbook-to-man, Sat 02 Feb 2008, 23:15
