debian/00debian.jl  etc/X11/sawfish/site-init.d
debian/00menu.jl    etc/X11/sawfish/site-init.d
debian/50cursors.jl etc/X11/sawfish/site-init.d
sawfish.el   usr/share/emacs/site-lisp/sawfish
usr/bin/sawfish
usr/bin/sawfish-about
usr/bin/sawfish-client
usr/bin/sawfish-config
usr/lib
usr/share/gnome/wm-properties/sawfish-wm.desktop
usr/share/man/man1
usr/share/sawfish/sawfish.png
usr/share/xsessions/sawfish.desktop
