#!/bin/sh

xprop -root -remove _NET_NUMBER_OF_DESKTOPS \
    -remove _NET_DESKTOP_NAMES \
    -remove _NET_CURRENT_DESKTOP 2> /dev/null

export WINDOW_MANAGER=$(which sawfish)

exec $WINDOW_MANAGER &
sleep 0.1
exec mate-session $@

