** tile

   Tilings for your workspaces. These are the exported interactive
   commands:

   - =tile-workspace= Tiles the current workspace with the active,
     registered tiling, if any.
   - =next-tiling= Cycles through available tilings for this workspace.
   - =increase-max-windows=, =decrease-max-windows= For tall tiling,
     increases/decreases the number of visible windows.
   - =increase-max-cols=, =decrease-max-cols= For column tiling,
     increases/decreases the number of columns.
   - =tall-rotate-left=, =tall-rotate-left= For tall tiling, rotate the
     tile left or right.

   Currently there are 2 tilings available:

   - *tall tile* Use =tall-tiling= to add to a given workspace. It works
     as xmonad's tall layout: one master window on the left, and the
     rest stacked on its right. The function takes a workspace number
     as its first argument plus the following keyword arguments:
     - =width= The master window will take (screen-width)/width pixels
       (default: 2).
     - =top=, =bottom= Top and bottom margins, in pixels (default: 0).
     - =gap= Spacing between adjacent windows, in pixels (default: 0).
     - =max= Maximum number of visible windows (default: 3).
     - =auto= A boolean indicating whether tiling should happen
       automatically whenever a new window is created (default: #t).
     - =right= A boolean indicating whether the main window should be
       placed to the right rather than to the left side (default: #f).
     - =master= A function taking a window and returning a boolean
       indicating whether the given window can occupy the main pane
       (default: =(lambda () #t)=).

   - *column tile* Divide the screen in the given number of columns and
     distributed windows among them. All columns have the same width
     and the window width is resized to fit in (its height is left
     untouched). The function to register a column tiling is
     =col-tiling=, which again takes the workspace number as its first
     argument and the following keyword args:
     - =cols= number of columns (default: 3)
     - =top=, =bottom=, =gap= as above.
     - =auto= as above

   Sample usage:

   #+BEGIN_SRC
     ;; Tiling
     (require 'sawfish.wm.tile.tile)
     (tall-tiling 0 #:width 1.75 #:top 0 #:bottom 0 #:gap 3 #:max 3)
     (col-tiling 0 #:top 0 #:bottom 0 #:gap 3 #:cols 3)
     (bind-keys global-keymap
		"C-S-KP_Add" 'increase-max-windows
		"C-S-KP_Subtract" 'decrease-max-windows
		"C-M-KP_Add" 'increase-cols
		"C-M-KP_Subtract" 'decrease-cols
		"C-M-Right" 'tall-rotate-right
		"C-M-Left" 'tall-rotate-left
		"C-F11" 'next-tiling)
   #+END_SRC
